#include "tile.h"

#include "manager.h"

// Hardcoded map layout: Subway Station (Platforms, Tracks, Gravel)
static const TileType default_map[MAP_HEIGHT][MAP_WIDTH] = {
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_GRAVEL,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_GRAVEL,   TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL},
    {TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT},
    {TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT},
    {TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL},
    {TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT,
     TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT, TILE_TRACK_LEFT},
    {TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT,
     TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT, TILE_TRACK_RIGHT},
    {TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL,
     TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL, TILE_GRAVEL},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
    {TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM,
     TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM, TILE_PLATFORM},
};

void tilemap_init(struct tilemap* tm) {
  for (int y = 0; y < MAP_HEIGHT; y++) {
    for (int x = 0; x < MAP_WIDTH; x++) {
      tm->tiles[y][x] = default_map[y][x];
    }
  }
}

void tilemap_draw(const struct tilemap* tm) {
  struct manager* mgr = manager_get_global();
  for (int y = 0; y < MAP_HEIGHT; y++) {
    for (int x = 0; x < MAP_WIDTH; x++) {
      Texture2D tex;
      switch (tm->tiles[y][x]) {
      case TILE_GRAVEL:
        tex = mgr->gravel_tex;
        break;
      case TILE_TRACK_LEFT:
        tex = mgr->track_left_tex;
        break;
      case TILE_TRACK_RIGHT:
        tex = mgr->track_right_tex;
        break;
      case TILE_PLATFORM:
        tex = mgr->platform_tex;
        break;
      default:
        tex = mgr->gravel_tex;
        break;
      }

      // Draw scaled texture to fill the 32x32 tile area
      Rectangle source = {0.0f, 0.0f, (float)tex.width, (float)tex.height};
      Rectangle dest = {(float)x * TILE_SIZE, (float)y * TILE_SIZE,
                        (float)TILE_SIZE, (float)TILE_SIZE};
      Vector2 origin = {0.0f, 0.0f};
      DrawTexturePro(tex, source, dest, origin, 0.0f, WHITE);
    }
  }
}

bool isWalkable(const struct tilemap* tm, int tile_x, int tile_y) {
  if (tile_x < 0 || tile_x >= MAP_WIDTH || tile_y < 0 || tile_y >= MAP_HEIGHT) {
    return false;
  }
  // All tiles are now walkable
  return true;
}
